# Generated by Django 5.2.4 on 2025-08-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MpesaDarajaapi', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transaction_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
